#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:$HOME/.bin
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
export HADOOP_HOME="/etc/hadoop"
export HADOOP_CONF_DIR="/etc/hadoop/conf"
export EDITOR="vi"
export VISUAL="vi"

alias ipython='ipython --TerminalInteractiveShell.highlighting_style="rrt"'
alias cdgo='cd $GOPATH/src'
