#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GOPATH=$HOME/code/go
export HADOOP_HOME="/etc/hadoop"
export HADOOP_CONF_DIR="/etc/hadoop/conf"
export EDITOR="vi"
export VISUAL="vi"

alias ipython='ipython --TerminalInteractiveShell.highlighting_style="rrt"'
alias cdgo='cd $GOPATH/src'

if [[ "$TERM" == "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
fi
